export { default as BasicInformationSection } from './BasicInformationSection';
export { default as PublicationDetailsSection } from './PublicationDetailsSection';
export { default as PhysicalDescriptionSection } from './PhysicalDescriptionSection';
export { default as AdditionalDetailsSection } from './AdditionalDetailsSection';
export { default as SpecializedFieldsTabs } from './SpecializedFieldsTabs';
export { default as CoverImageSection } from './CoverImageSection';
export { default as StatusToggleSection } from './StatusToggleSection';
export { default as QuickAddModals } from './QuickAddModals';
export { default as CatalogFormTabs } from './CatalogFormTabs';
export { default as ItemInfoTabContent } from './ItemInfoTabContent';
export { default as DetailTabContent } from './DetailTabContent';
export { default as JournalTabContent } from './JournalTabContent';
export { default as ThesisTabContent } from './ThesisTabContent';
export type { TabType } from './CatalogFormTabs';
